# ~/.config/hypr/hyprlock.conf

general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(0d0d0dff)   # Casi negro, como tu bar
}

# HORA
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    color = rgba(ffffffff)

    position = 0, 120
    halign = center
    valign = center
}

# FECHA
label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    color = rgba(ffffff88)

    position = 0, 50
    halign = center
    valign = center
}

# CAMPO DE CONTRASEÑA — estilo píldora
input-field {
    monitor =
    size = 220, 42
    rounding = 100          # Máximo redondeo = píldora perfecta
    outline_thickness = 0   # Sin borde, igual que tus módulos

    outer_color = rgba(00000000)
    inner_color = rgba(ffffff18)  # Blanco muy transparente
    font_color = rgba(ffffffff)
    font_family = JetBrainsMono Nerd Font
    font_size = 14

    placeholder_text = <>   # Vacío, minimalista
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    fail_color = rgba(ff6666ff)
    fail_text =             # Sin texto de error

    position = 0, -60
    halign = center
    valign = center
}
