# Pantalla apagada a los 5 min
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Bloqueo a los 6 min
listener {
    timeout = 300
    on-timeout = hyprlock
}
